[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="currentPage" type="java.lang.String" --]
[#-- @ftlvariable name="user" type="ru.itmo.web.hw4.model.User" --]
[#-- @ftlvariable name="users" type="ru.itmo.web.hw4.model.User[]" --]
[#-- @ftlvariable name="post" type="ru.itmo.web.hw4.model.Post" --]
[#-- @ftlvariable name="posts" type="ru.itmo.web.hw4.model.Post[]" --]
