[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="message" type="java.lang.String" --]
[#-- @ftlvariable name="user" type="ru.itmo.wp.domain.User" --]
[#-- @ftlvariable name="users" type="ru.itmo.wp.domain.User[]" --]
[#-- @ftlvariable name="notice" type="ru.itmo.wp.domain.Notice" --]
[#-- @ftlvariable name="notices" type="ru.itmo.wp.domain.Notice[]" --]
